service: nest-graphql-prisma

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs16.x
  environment:
    POSTGRESQL_URL: ${env:POSTGRESQL_URL}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: post
          path: graphql

package:
  exclude:
    - node_modules/**
    - venv/**
